<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PU-SDSG8221-04" name="Login Test" tests="1" failures="1" timestamp="21 Nov 2018 06:39:32 GMT" time="62.463" errors="0">
  <testcase name="loginTest" time="51.647" classname="com.qtpselenium.rediff.hybrid.testcases.portfoliosuite.LoginTest">
    <failure type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at com.qtpselenium.rediff.hybrid.driver.DriverScript.executeKeywords(DriverScript.java:75)
	at com.qtpselenium.rediff.hybrid.testcases.portfoliosuite.LoginTest.loginTest(LoginTest.java:34)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: The following asserts failed:
	WebElement not found - username_id	WebElement not found - username_id
	at com.qtpselenium.rediff.hybrid.keywords.GenericKeywords.reportFailure(GenericKeywords.java:323)
	at com.qtpselenium.rediff.hybrid.keywords.GenericKeywords.getObject(GenericKeywords.java:277)
	at com.qtpselenium.rediff.hybrid.keywords.AppKeywords.login(AppKeywords.java:37)
	... 26 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Login Test -->
